### ISSUE TITLE
Bootstrapped standard errors for the copula

### ISSUE THREAD

**Issue by gustafsoldan** [4350/grandslam#10]
I have sent the bootstraps I have done so far for the skewed-t. Take a look at them and see if they are starting to resemble a distribution, in that case we might decide to move on to some of the other copula specifications for now, so that they have some numbers too in the draft.

**Comment by gustafsoldan** [comment]
Other copula specifications will not have standard errors in this draft.

**Comment by gustafsoldan** [comment]
This is ready 👍

**Comment by victorandree** [comment]
We need 1) bootstraps for other models and 2) more bootstraps. Low significance on skewness parameters as it looks now.
