### ISSUE TITLE
Correlation graphs over time

### ISSUE THREAD

**Issue by victorandree** [4350/grandslam#12]

**Comment by victorandree** [comment]
I can do this. Are we just talking about rolling windows of correlations on the empirical data?

**Comment by gustafsoldan** [comment]
Yes, but what we want is rather graphs of the copula's estimation of correlations in-sample. The other empirical is already the draft. Not sure if prioritized for draft.

**Comment by victorandree** [comment]
See code in `correlations` in wimbledon and `do_correlations` in grandslam. Use Correlation series and Omega for the expectation

**Comment by victorandree** [comment]
![copula_dynamic_ghskt](https://cloud.githubusercontent.com/assets/52588/19416819/aef4d43a-939a-11e6-9957-815b88d503dd.png)

Boom.
