### ISSUE TITLE
Fix graph colors of lines

### ISSUE THREAD

**Issue by victorandree** [4350/grandslam#2]

**Comment by victorandree** [comment]
Ideally you'd want colors that 1) print OK in black-and-white 2) look good and 3) work for the color blind. The site [colorbrewer2.org](http://colorbrewer2.org) can help out. Honestly, a sequential scheme might work such as [the blue one](http://colorbrewer2.org/#type=sequential&scheme=YlGnBu&n=4).

We might also be boring and simply use linetype differentiation with all blacks.

**Comment by gustafsoldan** [comment]
This is old, I'm quite happy now with the look of the scheme we added in theme_Publication().
