### ISSUE TITLE
Threshold Correlation Story

### ISSUE THREAD

**Issue by gustafsoldan** [4350/grandslam#22]
Old heading:

Break out the threshold correlation graphs and describe in much more detail what is asymmetry and what is tail dependence, and what we should expect to see in Gaussian setting.
- [x] **IMPORTANT**: Why are threshold correlations not the same?
  
  It's an issue with plotting.

---
- [ ] Re-run threshold correlations on empirical data (new GARCH)
- [ ] Re-run threshold correlations from constant copulas with updated GARCH models (full-sample). 
  
    This requires re-simulating `stdresid` from constant copula models that have been estimated. The existing simulations are based on an old version of the GARCH specifications.
- [ ] Threshold correlations go from 10th to 90th percentiles (x-axis)
- [ ] Add horizontal line for the sample correlation

---
- [ ] Layout threshold correlation graphs. Let's put scatter plots to the left of threshold correlations, column wise.

**Comment by gustafsoldan** [comment]
I think we include this or something similar to explain what threshold corr is graphically. At least this was the kind of graph that made me understand it better 
![threshold_explain](https://cloud.githubusercontent.com/assets/11066719/19556050/ada76584-96bf-11e6-8a5c-74cf1685299a.png)

**Comment by victorandree** [comment]
Make sure #39 is properly ignored.
