### ISSUE TITLE
Prove volatility clustering and leverage effects in marginal series

### ISSUE THREAD

**Issue by gustafsoldan** [4350/grandslam#26]

**Comment by gustafsoldan** [comment]
![image](https://cloud.githubusercontent.com/assets/11066719/19579979/a02efe4e-9723-11e6-8e02-2ed75f489cb5.png)
GJRGARCH or no? Ofc we can do for only Mkt asthat's where sign bias is an issue..

**Comment by victorandree** [comment]
Did we do this for CMA? I mean, you're not getting rid of significance at 10% level with GJR (9.76 < 10)?

**Comment by gustafsoldan** [comment]
I've had a 5% cut-off in mind. I think it's fine.
