### ISSUE TITLE
CDB number 3

### ISSUE THREAD

**Issue by victorandree** [4350/grandslam#3]
- [x] Compute optimal CDB for:
  - [x] All - no convergence for t = 1873, 1883
  - [x] Modern - running on Gustaf's computer
  - [x] HML
  - [x] RMW
  - [x] CMA
  - [x] RMW+HML
  - [x] RMW+CMA
- [x] Compute EW CDB for each strategy
- [x] Visualize, facet grids, where each facet has optimal and EW:
  - [x] All/HML/Modern
  - [x] HML/RMW/CMA

**Comment by victorandree** [comment]
What is CDB number 3? Are we just talking about all, modern and classic or something else? @gustafsoldan

**Comment by gustafsoldan** [comment]
Yes, however I think it might be interesting to do a few more things relating to CDB:
1) Equal weights. This shows how much dynamic weighting really matters. Christoffersen also does this
2) Mean-variance weights, when we have such weights
3) Just out of curiosity, how would the current optimization for CDB look with 5 factors if we do (Mkt.RF, HML, SMB, Mom, RMW) in one and (Mkt.RF, HML, SMB, Mom, CMA). They should be worse than the (Mkt.RF, SMB, Mom, RMW, CMA) right?

**Comment by victorandree** [comment]
1. Right - should be quick to do as there's no optimization.
2. Feels like this should be pretty close to max(CDB) for any given universe. Isn't the tangency portfolio the one that gives you maximum diversification benefit (not necessarily in terms of ES, however, which I guess might make the difference).
3. It must be worse or equal, as you essentially don't have access to one diversifier (which relates to my critique that classic value is 1 and modern is 2). So, yeah, I think this makes sense. I'll set it up and let it run tonight.

Incidentally, visualizing all of this quickly gets messy because of all the possible combinations and the fact that they're not _that_ different. Probably makes sense to do facet grid for each "universe" (all, classic, modern, no RMW, no CMA) with one line for optimized and one for EW in each graph.

**Comment by victorandree** [comment]
Doing this for CMA is getting stuck at t = 712 even with the `1e-6` step thing. I'll let it run over night and check in the morning...

**Comment by victorandree** [comment]
Troublesome issue arose with optimized HML being outperformed by EW HML in some cases. Code has been revised and must re-run. I had also made some errors to the RMW/CMA calculations.

**Comment by victorandree** [comment]
3 CDB graphs have been added to results and loosely discussed.
