### ISSUE TITLE
Quantile time plot

### ISSUE THREAD

**Issue by victorandree** [4350/grandslam#34]
Correlations don't surge in bad times. Does that also rule out that bad realizations don't happen at the same time?

Paolo touched on this in conversations with me – a simple analysis is to see when the worst 10% of each series have realized. In a time series plot, you could just mark where they happened; say highlighting bottom 10% in red and top 10% in green for each series.

Is this different to threshold correlations? Kinda yeah a little bit, I think. It's not exactly a rigorous analysis but it could be revealing. Or?

**Comment by gustafsoldan** [comment]
![below_above_quantile](https://cloud.githubusercontent.com/assets/11066719/19527261/a55934a4-9627-11e6-8b8a-ff7d478a365d.png)
So yeah, they don't take huge losses in bad times. We can do the same exercise for the MV optimized portfolios. They will look even better

**Comment by victorandree** [comment]
Hm, I don't see where the percentiles are? Or... is that what we're seeing? I.e. the plot is zero for 80% (doesn't look like it???)?

**Comment by gustafsoldan** [comment]
Actually I'm pretty confident is 80% of the data. Here 100%
![below_above_quantile_all](https://cloud.githubusercontent.com/assets/11066719/19532419/e9015ab0-963b-11e6-82b6-a72a28f0197c.png)
