### ISSUE TITLE
Overall method story

### ISSUE THREAD

**Issue by gustafsoldan** [4350/grandslam#35]
- [x] Diagnostic of factor returns. Find: autocorr, vol clustering, leverage effect, fat tails
  5 lags everywhere
- [x] Autocorr weighted LB
  rugarch:::.weightedBoxTest()
  WeightedPortTest package
- [x] ARCH, ARCH LM weighted
  rugarch:::.weightedarchlmtest()
  WeightedPortTest package

---
- [ ] How to model? GARCH. Motivate which used.

---
- [x] Table normal errors w/wo gjr, sign bias test at bottom of table. Shift normal to appendix?rugarch:::.signbiasTest()

make this into function:

```
.signbiasTest = function(object)
{
    if(is(object, "uGARCHfilter")) z = object@filter$z else z = z = object@fit$z
    res = as.numeric(residuals(object))
    z2 = z^2
    n = length(z)
    zminus = as.integer(res<0)
    zplus = 1-zminus
    czminus = zminus*res
    czplus = zplus*res
    cz = cbind(rep(1, n), zminus, czminus, czplus)
    cz = cz[1:(n-1),]
    z2 = matrix(z2[2:n],ncol = 1)
    cm = data.frame(y = z2, const = cz[,1], zminus = cz[,2], czminus = cz[,3], czplus = cz[,4])
    fitA = lm(y~const+zminus+czminus+czplus-1, data = cm)
    resA = residuals(fitA)
    sgmatrix = matrix(ncol = 3, nrow = 4)
    rownames(sgmatrix) = c("Sign Bias","Negative Sign Bias","Positive Sign Bias","Joint Effect")
    colnames(sgmatrix) = c("t-value","prob","sig")
    sgmatrix[1:3,1:2] = abs(summary(fitA)$coef[2:4,3:4])
    jeffect = .linear.hypothesis(fitA, c("zminus = 0", "czminus = 0","czplus  =  0"), test  =  "Chisq")
    sgmatrix[4,1] = jeffect[5]$Chisq[2]
    sgmatrix[4,2] = jeffect[6][2,]
    sgmatrix = as.data.frame(sgmatrix)
    sgmatrix[,3] = .stars(sgmatrix[,2])
    return(sgmatrix)
}
```

---
- [x] Diagnose this model. Find white noise, no evidence of misspecification.
- [x] LB test residuals
- [x] ARCH LM test residuals
- [x] Sign bias test residuals
- [x] QQ plot residuals

---

- [ ] Check dependence in residuals - find dependence.
  - [ ] We have wanted to say as much as possible at the univariate level. It is not enough.
  - [ ] Threshold correlations
  - [ ] Rolling correlations
  - [ ] Don't do reverse threshold correlations, but make sure to include points of #39 in the story.

---

- [ ] How to model? Copula. Motivate why. Motivate which copula.
  - [ ] It is precisely because we have a copula that we have been able to do the univariate modeling first; otherwise we would have had to use e.g. DCC/BEKK.
  - [ ] This really is a parsimonious way of doing things.
  - [ ] Copula estimation is done using quasi maximum likelihood (cf #38).

---
- [ ] Diagnose the copula model.

**Comment by victorandree** [comment]
Interleaving data/method/results, maybe we can do something like this:

## Data
1.  Summary
   1.  Data
   2.  QQ-plots
   3.  Commentary
      1. Serial Correlation 
      2. Excess Skewness, Kurtosis and QQ-plots show non-normal
      3. Volatility clustering
2.  Correlations
   1.  Comment on but leave for later part

## Modeling Factor Returns
1.  Why GARCH model
   1.  Capture ARMA
   2.  Volatility Clustering
   3.  Leverage Effect
   4.  Non-normality of residuals
2.  Estimated GARCH model
   1.  Diagnostics
   2.  Effects are gone; model is good
   3.  Normal model is not good

## Modeling Joint Behavior
1.  Threshold Correlations
   1.  Method
   2.  Plots.
   3.  Difference between series and residuals
   4.  Weaker -- but still there: A lot of dependency is
      captured by ARMA-GARCH effects.
2.  Copula model to capture tail dependency
   1.  Method of Copula model
   2.  Estimation of Copula model
3.  Special Case of Constant Copula
   1.  Diagnostics
   2.  Skewed t threshold correlations better
   3.  Notably Gaussian does not
4.  Dynamic Copula Model
   1.  Diagnostics
   2.  Why do we prefer symmetric t (?)
   3.  Correlation patterns over time

## Putting the model to work
1.  Short sample estimation
2.  Out-of-sample performance
3.
