### ISSUE TITLE
Threshold Correlations on GARCH stdresid with symmetric t and Gaussian errors

### ISSUE THREAD

**Issue by victorandree** [4350/grandslam#36]
Let's "hope" there's still asymmetry in the threshold correlations.

**Comment by gustafsoldan** [comment]
Do you mean copula here?

What I just did is replace the GJRGARCH with GARCH for HML, SMB, Mom, RMW, as described in another issue. This gives nearly identical results. For new best garch's see recently committed do_garch_choose

**Comment by victorandree** [comment]
No, we're testing GARCH with Gaussian, Student's t and skewed Student's t right? I'm hoping there's asymmetric threshold correlations in the standardized residuals for all those distributions, too.

**Comment by gustafsoldan** [comment]
Not an issue. They are highly similar.

**Comment by gustafsoldan** [comment]
![threshold_garch_stdres_garch_ghst rdata_nonvalue](https://cloud.githubusercontent.com/assets/11066719/19626264/d183461a-992d-11e6-9e57-ef011d66de62.png)
![threshold_garch_stdres_garch_ghst rdata_value](https://cloud.githubusercontent.com/assets/11066719/19626261/d1805f0e-992d-11e6-8aa1-bb82edfcb565.png)
![threshold_garch_stdres_garch_norm rdata_nonvalue](https://cloud.githubusercontent.com/assets/11066719/19626266/d18586f0-992d-11e6-9680-f7ab9af24317.png)
![threshold_garch_stdres_garch_norm rdata_value](https://cloud.githubusercontent.com/assets/11066719/19626262/d182e3f0-992d-11e6-84c0-e46fc5a2b323.png)
![threshold_garch_stdres_garch_std rdata_nonvalue](https://cloud.githubusercontent.com/assets/11066719/19626263/d1832f5e-992d-11e6-9519-7494af5aeddc.png)
![threshold_garch_stdres_garch_std rdata_value](https://cloud.githubusercontent.com/assets/11066719/19626265/d1848b74-992d-11e6-93b3-d6f1362df377.png)
![threshold_garch_stdres_gjrgarch_ghst rdata_nonvalue](https://cloud.githubusercontent.com/assets/11066719/19626267/d1983ade-992d-11e6-9294-e001f7064cba.png)
![threshold_garch_stdres_gjrgarch_ghst rdata_value](https://cloud.githubusercontent.com/assets/11066719/19626268/d19a6930-992d-11e6-8b87-9c11092a1e06.png)
![threshold_garch_stdres_gjrgarch_norm rdata_nonvalue](https://cloud.githubusercontent.com/assets/11066719/19626272/d19f50f8-992d-11e6-821d-d11f5fbb062f.png)
![threshold_garch_stdres_gjrgarch_norm rdata_value](https://cloud.githubusercontent.com/assets/11066719/19626271/d19e04aa-992d-11e6-90a5-84fa3922a5ba.png)
![threshold_garch_stdres_gjrgarch_std rdata_nonvalue](https://cloud.githubusercontent.com/assets/11066719/19626270/d19d026c-992d-11e6-9a63-7dab555b58cb.png)
![threshold_garch_stdres_gjrgarch_std rdata_value](https://cloud.githubusercontent.com/assets/11066719/19626269/d19c6848-992d-11e6-8989-8b82d2004634.png)
