### ISSUE TITLE
Simulate constant copula data

### ISSUE THREAD

**Issue by victorandree** [4350/grandslam#4]

**Comment by victorandree** [comment]
This is primarily for threshold correlation purposes, right?

**Comment by gustafsoldan** [comment]
Yes. I think the threshold correlations from simulated data will be our main way of motivating our choice of copula.

**Comment by victorandree** [comment]
Ok, I will simulate standardized residuals from Gaussian, Student's t and Skewed t best-fitting copulas estimated on the whole dataset. 100k per copula?

**Comment by gustafsoldan** [comment]
If that's what we used for the others it makes sense to be consistent.

**Comment by victorandree** [comment]
I did 10k per day for the dynamic ones. The distribution is obviously constant for the constant copulas so it's just a question of how much you want for the tails....
