### ISSUE TITLE
AUM regressor

### ISSUE THREAD

**Issue by victorandree** [4350/grandslam#5]
To do this in the copula, we have to:
1. Think about how generally to support it. Probably best way to follow Christoffersen appendix as it is the most general and generally straightforward way to do it.
2. Obviously rewrite copula.R to support it. Involves adding the coefficient (phi something?), updating how Omega is computed and obviously the Q formula. Both the series of regressors must be passed along everywhere, as well as any coefficients in the matrix, as well as the phi-coefficient.
3. Fix everything else that would be affected by it.

**Comment by gustafsoldan** [comment]
In our gameball draft mail to Michael, we will ask him for access to the Lipper database.
