### ISSUE TITLE
OOS in CDB, how

### ISSUE THREAD

**Issue by gustafsoldan** [4350/grandslam#54]

**Comment by gustafsoldan** [comment]
- MV oos weights in full sample CDB, what was the "realized CDB"
- either CDB to MV, MV to CDB. differently strong between HML and CMA exclusions (how is MV in terms of oos tail diversification)

**Comment by victorandree** [comment]
Gustaf, ditt flum. Detta gör vi:
- [ ] OOS-MV weights i full-sample CDB => Results. 5 factor, 6 factors - excl HML, excl CMA, excl RMW.
