### ISSUE TITLE
Add sources for equal weights as a strategy

### ISSUE THREAD

**Issue by gustafsoldan** [4350/grandslam#59]

**Comment by gustafsoldan** [comment]
https://www.robeco.com/en/professionals/insights/quantitative-investing/factor-investing/seminar/how-factor-investing-fits-into-active-vs-passive.jsp

**Comment by victorandree** [comment]
Both in introduction and mean-variance optimization

**Comment by gustafsoldan** [comment]
[EDHEC-Risk_Publication_Risk_Allocation.pdf](https://github.com/4350/grandslam/files/606687/EDHEC-Risk_Publication_Risk_Allocation.pdf)
[MSCI Diversified Multi-Factor Indexes.pdf](https://github.com/4350/grandslam/files/606688/MSCI.Diversified.Multi-Factor.Indexes.pdf)
[MSCI notes.txt](https://github.com/4350/grandslam/files/606689/MSCI.notes.txt)
[Robeco online.txt](https://github.com/4350/grandslam/files/606693/Robeco.online.txt)
[Blackrock notes.txt](https://github.com/4350/grandslam/files/606691/Blackrock.notes.txt)
[BlackRock.pdf](https://github.com/4350/grandslam/files/606690/BlackRock.pdf)
[edhec notes.txt](https://github.com/4350/grandslam/files/606692/edhec.notes.txt)

**Comment by gustafsoldan** [comment]
take out vanguard, they actually think that market cap should be the starting point anyways
