### ISSUE TITLE
Model selection / GoF

### ISSUE THREAD

**Issue by victorandree** [4350/grandslam#9]

**Comment by victorandree** [comment]
@gustafsoldan You did this, right? And it seems that constant Gaussian is actually preferred? ...

**Comment by gustafsoldan** [comment]
By AIC and BIC yes. 

LR test still pending, but depends on non-standard statistics for nested models. Can compare to standard statistics as starting points. 

We might just select between models as Christoffersen (2012) do, by looking at the significance of e.g. degrees of freedom to choose t and skewness parameters to choose skewed. See Patton (2012) for info on parameter restrictions in nested models.

**Comment by gustafsoldan** [comment]
- [ ] Patton style model selection
- [ ] Discuss LR test feasibility

**Comment by gustafsoldan** [comment]
I made a mistake by taking logs of what was already log likelihood 👎 

Now BIC is much more reasonable, prefers the dynamic t. Results in paper. Will be the only model selection criterion.
